// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Data;

#nullable disable

namespace TMS.Migrations
{
    [DbContext(typeof(TourismContext))]
    [Migration("20250911044416_AddBookingStatusRefund")]
    partial class AddBookingStatusRefund
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 10000m,
                            BookingDate = new DateTime(2025, 9, 21, 10, 14, 15, 687, DateTimeKind.Local).AddTicks(2317),
                            ConfirmedOn = new DateTime(2025, 9, 11, 10, 14, 15, 687, DateTimeKind.Local).AddTicks(2339),
                            Seats = 2,
                            Status = 0,
                            TourPackageId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 8000m,
                            BookingDate = new DateTime(2025, 9, 16, 10, 14, 15, 687, DateTimeKind.Local).AddTicks(2344),
                            ConfirmedOn = new DateTime(2025, 9, 11, 10, 14, 15, 687, DateTimeKind.Local).AddTicks(2345),
                            Seats = 1,
                            Status = 0,
                            TourPackageId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TMS.Models.TourPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "3 Days/2 Nights Goa Tour",
                            ImageUrl = "/images/goa.jpg",
                            Price = 5000m,
                            Title = "Goa Beach Trip"
                        },
                        new
                        {
                            Id = 2,
                            Description = "5 Days Trekking in Himalayas",
                            ImageUrl = "/images/himalaya.jpg",
                            Price = 12000m,
                            Title = "Himalaya Trek"
                        },
                        new
                        {
                            Id = 3,
                            Description = "4 Days Houseboat Tour",
                            ImageUrl = "/images/kerala.jpg",
                            Price = 8000m,
                            Title = "Kerala Backwaters"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            Name = "Admin",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@test.com",
                            Name = "John Doe",
                            Password = "john123",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jane@test.com",
                            Name = "Jane Smith",
                            Password = "jane123",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("TMS.Models.Booking", b =>
                {
                    b.HasOne("TMS.Models.TourPackage", "TourPackage")
                        .WithMany()
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Customer")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TourPackage");
                });
#pragma warning restore 612, 618
        }
    }
}
